//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from ThemeStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class ThemeStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.ThemeStrings", typeof(ThemeStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string AppearancePanel_24HourTimeFormat => ResourceManager.GetString(nameof(AppearancePanel_24HourTimeFormat), _resourceCulture);

        public static string Theme_BlackboardScale80 => ResourceManager.GetString(nameof(Theme_BlackboardScale80), _resourceCulture);

        public static string Theme_BoardToolbarOpacity => ResourceManager.GetString(nameof(Theme_BoardToolbarOpacity), _resourceCulture);

        public static string Theme_BoardToolbarOpacityLeft => ResourceManager.GetString(nameof(Theme_BoardToolbarOpacityLeft), _resourceCulture);

        public static string Theme_BoardToolbarOpacityCenter => ResourceManager.GetString(nameof(Theme_BoardToolbarOpacityCenter), _resourceCulture);

        public static string Theme_BoardToolbarOpacityRight => ResourceManager.GetString(nameof(Theme_BoardToolbarOpacityRight), _resourceCulture);

        public static string Theme_BoardScaleLeft => ResourceManager.GetString(nameof(Theme_BoardScaleLeft), _resourceCulture);

        public static string Theme_BoardScaleCenter => ResourceManager.GetString(nameof(Theme_BoardScaleCenter), _resourceCulture);

        public static string Theme_BoardScaleRight => ResourceManager.GetString(nameof(Theme_BoardScaleRight), _resourceCulture);

        public static string Theme_Clear => ResourceManager.GetString(nameof(Theme_Clear), _resourceCulture);

        public static string Theme_CustomFloatingIconLabel => ResourceManager.GetString(nameof(Theme_CustomFloatingIconLabel), _resourceCulture);

        public static string Theme_CustomSplash_NotSelected => ResourceManager.GetString(nameof(Theme_CustomSplash_NotSelected), _resourceCulture);

        public static string Theme_CustomSplashImage => ResourceManager.GetString(nameof(Theme_CustomSplashImage), _resourceCulture);

        public static string Theme_CustomSplashImage_Desc => ResourceManager.GetString(nameof(Theme_CustomSplashImage_Desc), _resourceCulture);

        public static string Theme_CustomSplashTextPosition => ResourceManager.GetString(nameof(Theme_CustomSplashTextPosition), _resourceCulture);

        public static string Theme_CustomSplashTextPosition_Desc => ResourceManager.GetString(nameof(Theme_CustomSplashTextPosition_Desc), _resourceCulture);

        public static string Theme_Dark => ResourceManager.GetString(nameof(Theme_Dark), _resourceCulture);

        public static string Theme_EnableQuickPanel => ResourceManager.GetString(nameof(Theme_EnableQuickPanel), _resourceCulture);

        public static string Theme_EnableSplash => ResourceManager.GetString(nameof(Theme_EnableSplash), _resourceCulture);

        public static string Theme_FloatingBarButtonsTitle => ResourceManager.GetString(nameof(Theme_FloatingBarButtonsTitle), _resourceCulture);

        public static string Theme_FloatingBarIcon => ResourceManager.GetString(nameof(Theme_FloatingBarIcon), _resourceCulture);

        public static string Theme_FloatingBarOpacity => ResourceManager.GetString(nameof(Theme_FloatingBarOpacity), _resourceCulture);

        public static string Theme_FloatingBarOpacityInPPT => ResourceManager.GetString(nameof(Theme_FloatingBarOpacityInPPT), _resourceCulture);

        public static string Theme_FloatingBarOpacityInPPTHint => ResourceManager.GetString(nameof(Theme_FloatingBarOpacityInPPTHint), _resourceCulture);

        public static string Theme_FloatingBarScale => ResourceManager.GetString(nameof(Theme_FloatingBarScale), _resourceCulture);

        public static string Theme_FloatingIcon_CoolapkAbused => ResourceManager.GetString(nameof(Theme_FloatingIcon_CoolapkAbused), _resourceCulture);

        public static string Theme_FloatingIcon_CoolapkCrossEye => ResourceManager.GetString(nameof(Theme_FloatingIcon_CoolapkCrossEye), _resourceCulture);

        public static string Theme_FloatingIcon_CoolapkGreenHatDoge => ResourceManager.GetString(nameof(Theme_FloatingIcon_CoolapkGreenHatDoge), _resourceCulture);

        public static string Theme_FloatingIcon_CoolapkSmile => ResourceManager.GetString(nameof(Theme_FloatingIcon_CoolapkSmile), _resourceCulture);

        public static string Theme_FloatingIcon_CoolapkUnderwear => ResourceManager.GetString(nameof(Theme_FloatingIcon_CoolapkUnderwear), _resourceCulture);

        public static string Theme_FloatingIcon_IccBlackTransparent => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccBlackTransparent), _resourceCulture);

        public static string Theme_FloatingIcon_IccDark => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccDark), _resourceCulture);

        public static string Theme_FloatingIcon_IccDarkBreath => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccDarkBreath), _resourceCulture);

        public static string Theme_FloatingIcon_IccDefault => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccDefault), _resourceCulture);

        public static string Theme_FloatingIcon_IccNoShadow => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccNoShadow), _resourceCulture);

        public static string Theme_FloatingIcon_IccWhiteTransparent => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccWhiteTransparent), _resourceCulture);

        public static string Theme_FloatingIcon_TiebaEmoji => ResourceManager.GetString(nameof(Theme_FloatingIcon_TiebaEmoji), _resourceCulture);

        public static string Theme_GroupTitle => ResourceManager.GetString(nameof(Theme_GroupTitle), _resourceCulture);

        public static string Theme_Label => ResourceManager.GetString(nameof(Theme_Label), _resourceCulture);

        public static string Theme_Language_ChineseSimplified => ResourceManager.GetString(nameof(Theme_Language_ChineseSimplified), _resourceCulture);

        public static string Theme_Language_English => ResourceManager.GetString(nameof(Theme_Language_English), _resourceCulture);

        public static string Theme_Language_MemeChinese => ResourceManager.GetString(nameof(Theme_Language_MemeChinese), _resourceCulture);

        public static string Theme_Language_RestartHint => ResourceManager.GetString(nameof(Theme_Language_RestartHint), _resourceCulture);

        public static string Theme_LanguageLabel => ResourceManager.GetString(nameof(Theme_LanguageLabel), _resourceCulture);

        public static string Theme_Light => ResourceManager.GetString(nameof(Theme_Light), _resourceCulture);

        public static string Theme_Manage => ResourceManager.GetString(nameof(Theme_Manage), _resourceCulture);

        public static string Theme_QuickPalette_DoubleRow => ResourceManager.GetString(nameof(Theme_QuickPalette_DoubleRow), _resourceCulture);

        public static string Theme_QuickPalette_SingleRow => ResourceManager.GetString(nameof(Theme_QuickPalette_SingleRow), _resourceCulture);

        public static string Theme_QuickPanelBottomOffset => ResourceManager.GetString(nameof(Theme_QuickPanelBottomOffset), _resourceCulture);

        public static string Theme_QuoteSource => ResourceManager.GetString(nameof(Theme_QuoteSource), _resourceCulture);

        public static string Theme_QuoteSource_GaokaoBless => ResourceManager.GetString(nameof(Theme_QuoteSource_GaokaoBless), _resourceCulture);

        public static string Theme_QuoteSource_Hitokoto => ResourceManager.GetString(nameof(Theme_QuoteSource_Hitokoto), _resourceCulture);

        public static string Theme_QuoteSource_Mottos => ResourceManager.GetString(nameof(Theme_QuoteSource_Mottos), _resourceCulture);

        public static string Theme_QuoteSource_OsuQuotes => ResourceManager.GetString(nameof(Theme_QuoteSource_OsuQuotes), _resourceCulture);

        public static string Theme_QuoteSource_PhigrosTips => ResourceManager.GetString(nameof(Theme_QuoteSource_PhigrosTips), _resourceCulture);

        public static string Theme_ShowQuoteInWhiteboard => ResourceManager.GetString(nameof(Theme_ShowQuoteInWhiteboard), _resourceCulture);

        public static string Theme_ShowTimeInWhiteboard => ResourceManager.GetString(nameof(Theme_ShowTimeInWhiteboard), _resourceCulture);

        public static string Theme_Splash_Autumn => ResourceManager.GetString(nameof(Theme_Splash_Autumn), _resourceCulture);

        public static string Theme_Splash_Custom => ResourceManager.GetString(nameof(Theme_Splash_Custom), _resourceCulture);

        public static string Theme_Splash_Horse => ResourceManager.GetString(nameof(Theme_Splash_Horse), _resourceCulture);

        public static string Theme_Splash_Random => ResourceManager.GetString(nameof(Theme_Splash_Random), _resourceCulture);

        public static string Theme_Splash_Seasonal => ResourceManager.GetString(nameof(Theme_Splash_Seasonal), _resourceCulture);

        public static string Theme_Splash_Spring => ResourceManager.GetString(nameof(Theme_Splash_Spring), _resourceCulture);

        public static string Theme_Splash_Summer => ResourceManager.GetString(nameof(Theme_Splash_Summer), _resourceCulture);

        public static string Theme_Splash_Winter => ResourceManager.GetString(nameof(Theme_Splash_Winter), _resourceCulture);

        public static string Theme_SplashStyle => ResourceManager.GetString(nameof(Theme_SplashStyle), _resourceCulture);

        public static string Theme_System => ResourceManager.GetString(nameof(Theme_System), _resourceCulture);

        public static string Theme_UnfoldButtonIcon => ResourceManager.GetString(nameof(Theme_UnfoldButtonIcon), _resourceCulture);

        public static string Theme_UnfoldIcon_Arrow => ResourceManager.GetString(nameof(Theme_UnfoldIcon_Arrow), _resourceCulture);

        public static string Theme_UnfoldIcon_ClassicArrow => ResourceManager.GetString(nameof(Theme_UnfoldIcon_ClassicArrow), _resourceCulture);

        public static string Theme_UnfoldIcon_ClassicPen => ResourceManager.GetString(nameof(Theme_UnfoldIcon_ClassicPen), _resourceCulture);

        public static string Theme_UnfoldIcon_Stripe => ResourceManager.GetString(nameof(Theme_UnfoldIcon_Stripe), _resourceCulture);

        public static string Theme_AllowDragSidePanel => ResourceManager.GetString(nameof(Theme_AllowDragSidePanel), _resourceCulture);

        public static string Theme_Upload => ResourceManager.GetString(nameof(Theme_Upload), _resourceCulture);

        public static string Theme_UseLegacyFloatingBarUI => ResourceManager.GetString(nameof(Theme_UseLegacyFloatingBarUI), _resourceCulture);

        public static string Theme_ShowPenColorOnFloatingBarIcon => ResourceManager.GetString(nameof(Theme_ShowPenColorOnFloatingBarIcon), _resourceCulture);

        public static string Theme_CompactFloatingBar => ResourceManager.GetString(nameof(Theme_CompactFloatingBar), _resourceCulture);

        public static string Theme_CompactFloatingBarHint => ResourceManager.GetString(nameof(Theme_CompactFloatingBarHint), _resourceCulture);

        public static string Theme_HideFloatingBarBorder => ResourceManager.GetString(nameof(Theme_HideFloatingBarBorder), _resourceCulture);

        public static string Theme_HideFloatingBarBorderHint => ResourceManager.GetString(nameof(Theme_HideFloatingBarBorderHint), _resourceCulture);

        public static string Theme_UseBoardStyleFloatingToolbar => ResourceManager.GetString(nameof(Theme_UseBoardStyleFloatingToolbar), _resourceCulture);

        public static string Theme_UseBoardStyleFloatingToolbarHint => ResourceManager.GetString(nameof(Theme_UseBoardStyleFloatingToolbarHint), _resourceCulture);

        public static string Theme_WindowBackdrop => ResourceManager.GetString(nameof(Theme_WindowBackdrop), _resourceCulture);

        public static string Theme_WindowBackdrop_Acrylic => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Acrylic), _resourceCulture);

        public static string Theme_WindowBackdrop_Acrylic10 => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Acrylic10), _resourceCulture);

        public static string Theme_WindowBackdrop_Acrylic11 => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Acrylic11), _resourceCulture);

        public static string Theme_WindowBackdrop_Description => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Description), _resourceCulture);

        public static string Theme_WindowBackdrop_Mica => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Mica), _resourceCulture);

        public static string Theme_WindowBackdrop_None => ResourceManager.GetString(nameof(Theme_WindowBackdrop_None), _resourceCulture);

        public static string Theme_WindowBackdrop_Tabbed => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Tabbed), _resourceCulture);

        public static string Theme_WindowBackdrop_Transient => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Transient), _resourceCulture);

        public static string Theme_FloatingBarButtonsDescription => ResourceManager.GetString(nameof(Theme_FloatingBarButtonsDescription), _resourceCulture);

        public static string Theme_SelectCustomSplashImage => ResourceManager.GetString(nameof(Theme_SelectCustomSplashImage), _resourceCulture);

        public static string Theme_HitokotoCategory_Animation => ResourceManager.GetString(nameof(Theme_HitokotoCategory_Animation), _resourceCulture);

        public static string Theme_HitokotoCategory_Manga => ResourceManager.GetString(nameof(Theme_HitokotoCategory_Manga), _resourceCulture);

        public static string Theme_HitokotoCategory_Game => ResourceManager.GetString(nameof(Theme_HitokotoCategory_Game), _resourceCulture);

        public static string Theme_HitokotoCategory_Literature => ResourceManager.GetString(nameof(Theme_HitokotoCategory_Literature), _resourceCulture);

        public static string Theme_HitokotoCategory_Original => ResourceManager.GetString(nameof(Theme_HitokotoCategory_Original), _resourceCulture);

        public static string Theme_HitokotoCategory_FromWeb => ResourceManager.GetString(nameof(Theme_HitokotoCategory_FromWeb), _resourceCulture);

        public static string Theme_HitokotoCategory_Movie => ResourceManager.GetString(nameof(Theme_HitokotoCategory_Movie), _resourceCulture);

        public static string Theme_HitokotoCategory_Poetry => ResourceManager.GetString(nameof(Theme_HitokotoCategory_Poetry), _resourceCulture);

        public static string Theme_HitokotoCategory_NeteaseCloud => ResourceManager.GetString(nameof(Theme_HitokotoCategory_NeteaseCloud), _resourceCulture);

        public static string Theme_HitokotoCategory_Philosophy => ResourceManager.GetString(nameof(Theme_HitokotoCategory_Philosophy), _resourceCulture);

        public static string Theme_HitokotoCategory_Humor => ResourceManager.GetString(nameof(Theme_HitokotoCategory_Humor), _resourceCulture);

        public static string Theme_Hitokoto_SelectAll => ResourceManager.GetString(nameof(Theme_Hitokoto_SelectAll), _resourceCulture);

        public static string Theme_Hitokoto_CustomizeTitle => ResourceManager.GetString(nameof(Theme_Hitokoto_CustomizeTitle), _resourceCulture);

        public static string Theme_QuickPanelOpacity => ResourceManager.GetString(nameof(Theme_QuickPanelOpacity), _resourceCulture);

        public static string Theme_AutoCollapseQuickPanel => ResourceManager.GetString(nameof(Theme_AutoCollapseQuickPanel), _resourceCulture);

        public static string Theme_AutoCollapseQuickPanelDelay => ResourceManager.GetString(nameof(Theme_AutoCollapseQuickPanelDelay), _resourceCulture);

        public static string Theme_QuotePosition => ResourceManager.GetString(nameof(Theme_QuotePosition), _resourceCulture);

        public static string Theme_QuotePosition_TopLeft => ResourceManager.GetString(nameof(Theme_QuotePosition_TopLeft), _resourceCulture);

        public static string Theme_QuotePosition_TopRight => ResourceManager.GetString(nameof(Theme_QuotePosition_TopRight), _resourceCulture);

        public static string Theme_QuotePosition_BottomLeft => ResourceManager.GetString(nameof(Theme_QuotePosition_BottomLeft), _resourceCulture);

        public static string Theme_QuotePosition_BottomRight => ResourceManager.GetString(nameof(Theme_QuotePosition_BottomRight), _resourceCulture);

        public static string Theme_FloatingBarMenuOpacity => ResourceManager.GetString(nameof(Theme_FloatingBarMenuOpacity), _resourceCulture);

        public static string Theme_FloatingBarMenuOpacityInPPT => ResourceManager.GetString(nameof(Theme_FloatingBarMenuOpacityInPPT), _resourceCulture);

        public static string Theme_BoardMenuOpacity => ResourceManager.GetString(nameof(Theme_BoardMenuOpacity), _resourceCulture);
    }
}